runtime: go114

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /sw-import.js
  static_files: sw-import.js
  upload: sw-import.js

- url: /components
  static_dir: build/prod/components

- url: /node_modules/@polymer/sw-toolbox
  static_dir: node_modules/sw-toolbox

- url: /node_modules
  static_dir: build/prod/node_modules

- url: /
  static_files: build/prod/index.html
  upload: build/prod/index.html
  secure: always
