application: highdn-com
version: 2
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /bower_components
  static_dir: bower_components

- url: /components
  static_dir: components

- url: /sw-import.js
  static_files: sw-import.js
  upload: sw-import.js
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /.+
  script: _go_app
  secure: always
